apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: reviews
  namespace: {{ .Values.namespace }}
spec:
  host: reviews
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v3
      labels:
        version: v3
